name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Validar sintaxe do Docker Compose
      run: docker compose config

    - name: Build da imagem PHP personalizada
      run: docker build -t meu-projeto-php:latest -f Dockerfile.php .

    - name: Teste de integração (Subir ambiente)
      run: |
        docker compose up -d
        sleep 10
        docker compose ps